"use client";

import { useEffect, useRef, useState } from "react";
import CloseButton from "@/components/CloseButton";
import SourcePill from "@/components/SourcePill";

export default function PodcastPage() {
  const [podcastName, setPodcastName] = useState("");
  const [bannerUrl, setBannerUrl] = useState("");
  const [sourceLink, setSourceLink] = useState("");
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [speed, setSpeed] = useState(1);
  const [loaded, setLoaded] = useState(false);

  const audioRef = useRef<HTMLAudioElement | null>(null);
  const seekBarRef = useRef<HTMLDivElement>(null);

  const speeds = [1, 1.5, 2, 4];

  useEffect(() => {
    fetch("/api/podcast")
      .then((r) => r.json())
      .then((data) => {
        if (data.error) return;
        setPodcastName(data.podcast_name);
        setBannerUrl(data.podcast_banner_url);
        setSourceLink(data.topic_source);
        audioRef.current = new Audio(data.podcast_audio_url);
        audioRef.current.preload = "metadata";

        audioRef.current.addEventListener("loadedmetadata", () => {
          setDuration(audioRef.current!.duration);
        });
        audioRef.current.addEventListener("timeupdate", () => {
          setCurrentTime(audioRef.current!.currentTime);
        });
        audioRef.current.addEventListener("play", () => setIsPlaying(true));
        audioRef.current.addEventListener("pause", () => setIsPlaying(false));
        audioRef.current.addEventListener("ended", () => setIsPlaying(false));

        setLoaded(true);
      })
      .catch(console.error);

    return () => {
      if (audioRef.current) { audioRef.current.pause(); audioRef.current.src = ""; }
    };
  }, []);

  const togglePlay = () => {
    if (!audioRef.current) return;
    if (audioRef.current.paused) audioRef.current.play();
    else audioRef.current.pause();
  };

  const cycleSpeed = () => {
    const nextIdx = (speeds.indexOf(speed) + 1) % speeds.length;
    const newSpeed = speeds[nextIdx];
    setSpeed(newSpeed);
    if (audioRef.current) audioRef.current.playbackRate = newSpeed;
  };

  const skip = (seconds: number) => {
    if (!audioRef.current) return;
    audioRef.current.currentTime = Math.max(0, Math.min(duration, audioRef.current.currentTime + seconds));
  };

  const seekTo = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!seekBarRef.current || !audioRef.current) return;
    const rect = seekBarRef.current.getBoundingClientRect();
    const x = Math.max(0, Math.min(e.clientX - rect.left, rect.width));
    audioRef.current.currentTime = (x / rect.width) * duration;
  };

  const formatTime = (sec: number) => {
    sec = Math.max(0, Math.floor(sec));
    const m = Math.floor(sec / 60);
    const s = sec % 60;
    return `-${m}:${s.toString().padStart(2, "0")}`;
  };

  const percent = duration > 0 ? (currentTime / duration) * 100 : 0;

  return (
    <section className="relative h-screen w-screen overflow-hidden" style={{ background: "#ffc" }}>
      <CloseButton />

      {/* Banner image */}
      <div
        className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[500px] bg-cover bg-center bg-no-repeat transition-all duration-1000"
        style={{
          backgroundImage: bannerUrl ? `url(${bannerUrl})` : undefined,
          opacity: loaded ? 1 : 0,
        }}
      />

      {/* Mask gradient */}
      <div className="absolute -bottom-[5%] h-[60%] -left-[10%] w-[200%] rounded-[550px]" style={{ background: "linear-gradient(to bottom, white, white)", filter: "blur(60px)" }} />

      {/* Podcast name */}
      <p
        className="absolute top-[60%] left-1/2 -translate-x-1/2 text-3xl font-bold z-10 text-center font-[family-name:var(--font-parkinsans)] transition-opacity duration-700 max-sm:text-xl max-sm:top-[45%] max-sm:w-[80%]"
        style={{ opacity: loaded ? 1 : 0 }}
      >
        {podcastName}
      </p>
      <p className="absolute top-[70%] left-1/2 -translate-x-1/2 text-sm z-10 w-[80%] text-center font-[family-name:var(--font-parkinsans)] max-sm:top-[58%] max-sm:text-sm">
        This podcast is generated by Elixpo Copilot. There might be mistakes
      </p>

      {/* Source */}
      {sourceLink && (
        <div className="absolute top-[73%] left-1/2 -translate-x-1/2 z-10 flex items-center gap-2.5 max-sm:top-[64%]">
          <SourcePill sourceLink={sourceLink} />
        </div>
      )}

      {/* Playback zone */}
      <div className="absolute top-[85%] left-1/2 -translate-x-1/2 w-[30%] h-[100px] rounded-[25px] z-10 select-none max-lg:w-[50%] max-sm:w-[80%] max-sm:top-[75%]" style={{ background: "#1111118a", boxShadow: "0 12px 20px #1111116a" }}>
        {/* Seek range */}
        <div className="relative flex items-center w-[90%] h-[40%] left-[5%] top-[10%] gap-5">
          <button
            onClick={cycleSpeed}
            className="font-[family-name:var(--font-parkinsans)] font-bold rounded-lg px-2 py-0.5 mr-2.5 cursor-pointer transition-all duration-300"
            style={{ color: "#ffc" }}
          >
            {speed}x
          </button>
          <div
            ref={seekBarRef}
            onClick={seekTo}
            className="relative w-[75%] h-[5px] rounded-[10px] cursor-pointer mr-2.5"
            style={{ background: "#ffc" }}
          >
            <div className="absolute h-[5px] rounded-[20px] top-0 left-0" style={{ width: `${percent}%`, background: "#ddb581" }} />
            <div
              className="absolute w-[15px] h-[15px] rounded-full -top-[5px] z-[1] cursor-pointer"
              style={{ left: `${percent}%`, background: "rgb(50,40,19)", transform: "translateX(-50%)" }}
            />
          </div>
          <span className="font-[family-name:var(--font-parkinsans)] font-bold" style={{ color: "#ffc" }}>
            {formatTime(duration - currentTime)}
          </span>
        </div>

        {/* Controls */}
        <div className="relative flex items-center justify-between w-[50%] h-[40%] left-1/2 -translate-x-1/2 top-[10%]">
          <svg viewBox="0 0 24 24" className="w-[30px] h-[30px] cursor-pointer max-sm:w-[25px] max-sm:h-[25px]" onClick={() => skip(-10)}>
            <path d="M2.74999 2.5C2.33578 2.5 2 2.83579 2 3.25V8.75C2 9.16421 2.33578 9.5 2.74999 9.5H8.25011C8.66432 9.5 9.00011 9.16421 9.00011 8.75C9.00011 8.33579 8.66432 8 8.25011 8H4.34273C5.40077 6.60212 6.77033 5.4648 8.47169 4.93832C10.5381 4.29885 12.7232 4.35354 14.7384 5.10317C16.7673 5.85787 18.6479 7.38847 19.5922 9.11081C19.7914 9.47401 20.2473 9.607 20.6104 9.40785C20.9736 9.20871 21.1066 8.75284 20.9075 8.38964C19.7655 6.30687 17.5773 4.55877 15.2614 3.69728C12.9318 2.83072 10.4069 2.7693 8.02826 3.50536C6.14955 4.08673 4.65345 5.26153 3.49999 6.64949V3.25C3.49999 2.83579 3.1642 2.5 2.74999 2.5ZM8.95266 11.0278C9.27643 11.1186 9.50022 11.4138 9.50022 11.75V20.25C9.50022 20.6642 9.16443 21 8.75022 21C8.33601 21 8.00023 20.6642 8.00023 20.25V13.8328C7.61793 14.202 7.16004 14.5788 6.63611 14.8931C6.28093 15.1062 5.82024 14.9911 5.60713 14.6359C5.39402 14.2807 5.5092 13.82 5.86438 13.6069C6.53976 13.2017 7.10401 12.6421 7.50653 12.1678C7.70552 11.9334 7.85963 11.7261 7.96279 11.5793C8.01427 11.5061 8.05276 11.4483 8.07751 11.4103C8.08989 11.3913 8.0988 11.3772 8.10417 11.3687L8.10951 11.3602L8.11019 11.359C8.28503 11.072 8.629 10.9371 8.95266 11.0278ZM13.1988 12.629C13.7527 11.6377 14.6822 11 16.002 11C17.3218 11 18.2513 11.6377 18.8052 12.629C19.3266 13.5624 19.502 14.7762 19.502 16C19.502 17.2238 19.3266 18.4376 18.8052 19.371C18.2513 20.3623 17.3218 21 16.002 21C14.6822 21 13.7527 20.3623 13.1988 19.371C12.6774 18.4376 12.502 17.2238 12.502 16C12.502 14.7762 12.6774 13.5624 13.1988 12.629ZM14.5083 13.3606C14.1704 13.9654 14.002 14.8766 14.002 16C14.002 17.1234 14.1704 18.0346 14.5083 18.6394C14.8139 19.1863 15.2593 19.5 16.002 19.5C16.7447 19.5 17.1901 19.1863 17.4957 18.6394C17.8336 18.0346 18.002 17.1234 18.002 16C18.002 14.8766 17.8336 13.9654 17.4957 13.3606C17.1901 12.8137 16.7447 12.5 16.002 12.5C15.2593 12.5 14.8139 12.8137 14.5083 13.3606Z" fill="#ffc" />
          </svg>
          <svg viewBox="0 0 32 32" className="w-[30px] h-[30px] cursor-pointer max-sm:w-[25px] max-sm:h-[25px]" onClick={togglePlay}>
            {isPlaying ? (
              <path d="M7.25 29C5.45507 29 4 27.5449 4 25.75V7.25C4 5.45507 5.45507 4 7.25 4H10.75C12.5449 4 14 5.45507 14 7.25V25.75C14 27.5449 12.5449 29 10.75 29H7.25ZM21.25 29C19.4551 29 18 27.5449 18 25.75V7.25C18 5.45507 19.4551 4 21.25 4H24.75C26.5449 4 28 5.45507 28 7.25V25.75C28 27.5449 26.5449 29 24.75 29H21.25Z" fill="#ffc" />
            ) : (
              <path d="M12.2246 27.5373C9.89137 28.8585 7 27.173 7 24.4917V7.50044C7 4.81864 9.89234 3.1332 12.2256 4.45537L27.2233 12.9542C29.5897 14.2951 29.5891 17.7047 27.2223 19.0449L12.2246 27.5373Z" fill="#ffc" />
            )}
          </svg>
          <svg viewBox="0 0 24 24" className="w-[30px] h-[30px] cursor-pointer max-sm:w-[25px] max-sm:h-[25px]" onClick={() => skip(10)}>
            <path d="M21.25 2.5C21.6642 2.5 22 2.83579 22 3.25V8.75C22 9.16421 21.6642 9.5 21.25 9.5H15.7499C15.3357 9.5 14.9999 9.16421 14.9999 8.75C14.9999 8.33578 15.3357 8 15.7499 8H19.6573C18.5992 6.60212 17.2297 5.4648 15.5283 4.93832C13.4619 4.29885 11.2768 4.35354 9.26156 5.10317C7.23271 5.85787 5.35214 7.38846 4.40776 9.11081C4.20861 9.47401 3.75274 9.607 3.38955 9.40785C3.02635 9.20871 2.89336 8.75283 3.09251 8.38964C4.23451 6.30687 6.42268 4.55877 8.73861 3.69728C11.0682 2.83072 13.5931 2.7693 15.9717 3.50536C17.8504 4.08673 19.3465 5.26153 20.5 6.64949V3.25C20.5 2.83579 20.8358 2.5 21.25 2.5ZM16.0018 11C14.6821 11 13.7525 11.6377 13.1987 12.629C12.6772 13.5624 12.5019 14.7762 12.5019 16C12.5019 17.2238 12.6772 18.4376 13.1987 19.371C13.7525 20.3623 14.6821 21 16.0018 21C17.3216 21 18.2512 20.3623 18.805 19.371C19.3265 18.4376 19.5018 17.2238 19.5018 16C19.5018 14.7762 19.3265 13.5624 18.805 12.629C18.2512 11.6377 17.3216 11 16.0018 11ZM14.0019 16C14.0019 14.8766 14.1703 13.9654 14.5082 13.3606C14.8137 12.8137 15.2591 12.5 16.0018 12.5C16.7446 12.5 17.19 12.8137 17.4955 13.3606C17.8334 13.9654 18.0018 14.8766 18.0018 16C18.0018 17.1234 17.8334 18.0346 17.4955 18.6394C17.19 19.1863 16.7446 19.5 16.0018 19.5C15.2591 19.5 14.8137 19.1863 14.5082 18.6394C14.1703 18.0346 14.0019 17.1234 14.0019 16ZM9.50005 11.75C9.50005 11.4138 9.27626 11.1186 8.9525 11.0278C8.62884 10.9371 8.28486 11.072 8.11003 11.359L8.10935 11.3602L8.10401 11.3687C8.09864 11.3772 8.08972 11.3913 8.07735 11.4103C8.05259 11.4483 8.0141 11.5061 7.96263 11.5793C7.85946 11.7261 7.70536 11.9334 7.50637 12.1678C7.10384 12.6421 6.5396 13.2016 5.86422 13.6069C5.50903 13.82 5.39386 14.2807 5.60697 14.6359C5.82008 14.9911 6.28077 15.1062 6.63595 14.8931C7.15988 14.5788 7.61776 14.202 8.00007 13.8328V20.25C8.00007 20.6642 8.33585 21 8.75006 21C9.16427 21 9.50005 20.6642 9.50005 20.25V11.75Z" fill="#ffc" />
          </svg>
        </div>
      </div>
    </section>
  );
}
